#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" docker-jinja """

__author__ = "Johan Grok Andersson <Grokzen@gmail.com>"

import os
import sys

# Check if we are installed in the system already, otherwise update path
(prefix, bindir) = os.path.split(os.path.dirname(os.path.abspath(sys.argv[0])))
sys.path.append(prefix)

if bindir != 'bin':
    # Assume we are not yet installed
    sys.path.append(os.path.join(prefix, bindir, 'lib'))

if __name__ == "__main__":
    from djinja import cli
    cli.main()
